# Generated by Django 4.1.1 on 2023-03-20 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('postcode', models.CharField(max_length=128)),
                ('country', models.TextField(max_length=128)),
                ('size_squ_ft', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PointsChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tip')),
                ('user_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.activity')),
                ('user_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=128, unique=True)),
                ('score', models.CharField(max_length=128)),
                ('activity_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.useractivity')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.award')),
                ('meter_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.meterreading')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tip')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('score', models.CharField(max_length=128)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.location')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=128, unique=True)),
                ('points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.points')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activityList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.activitylist'),
        ),
    ]
