# Generated by Django 4.1.1 on 2023-03-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenger',
            old_name='userlink',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
