# Generated by Django 4.1.1 on 2023-03-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_challenger_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenger',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
