# Generated by Django 4.1.1 on 2023-04-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_lineitem_usercart_alter_challenger_postcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('TR', 'Time required'), ('TNR', 'Time not required')], default='TNR', max_length=4),
        ),
    ]
