# Generated by Django 4.1.1 on 2023-04-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='recordedTime',
            field=models.IntegerField(default=0),
        ),
    ]
