# Generated by Django 4.1.1 on 2023-04-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_lineitem_recordedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='challenger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.challenger'),
        ),
    ]
