# Generated by Django 4.1.1 on 2023-04-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_usercart_challenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='recordedTime',
            field=models.DateField(),
        ),
    ]
