# Generated by Django 4.1.1 on 2023-04-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_lineitem_recordedtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='recordedTime',
            new_name='dateRecorded',
        ),
    ]
