# Generated by Django 4.1.1 on 2023-03-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_riddles'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddles',
            name='r_id',
            field=models.IntegerField(default=1),
        ),
    ]
