# Generated by Django 4.1.1 on 2023-04-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_lineitem_checkedout'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='timeRecorded',
            field=models.TimeField(auto_now=True),
        ),
    ]
