# Generated by Django 4.1.1 on 2023-04-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_lineitem_timerecorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(default='TNR', max_length=4),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='timeRecorded',
            field=models.TimeField(),
        ),
    ]
