# Generated by Django 4.1.1 on 2023-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_activity_type_alter_lineitem_timerecorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
