# Generated by Django 4.1.1 on 2023-05-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_activity_type_alter_lineitem_timerecorded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddles',
            name='r_id',
        ),
        migrations.AddField(
            model_name='riddles',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
