# Generated by Django 4.1.1 on 2023-05-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_riddles_r_id_riddles_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddles',
            name='used',
        ),
        migrations.AddField(
            model_name='riddles',
            name='r_id',
            field=models.IntegerField(default=1),
        ),
    ]
