# Generated by Django 4.1.1 on 2023-05-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_riddles_used_riddles_r_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
