# Generated by Django 4.1.1 on 2023-05-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_location_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='faction',
        ),
    ]
